# Generated by Django 3.2.3 on 2021-05-28 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guruhlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeri', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Oqituvchi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=50)),
                ('familiya', models.CharField(max_length=50)),
                ('sharif', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('tugilgan_kun', models.DateTimeField()),
                ('ish_tajribasi', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sohalar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soha', models.CharField(max_length=100)),
                ('asosiy_soha', models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='main.sohalar')),
            ],
        ),
        migrations.CreateModel(
            name='TashkilotTurlari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tur', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UygaVazifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oxirgi_muddat', models.DateTimeField()),
                ('vazifa_matni', models.TextField(blank=True, default=None, null=True)),
                ('vazifa_oyi', models.CharField(max_length=20)),
                ('vazifa_kuni', models.IntegerField()),
                ('muddat_oyi', models.CharField(max_length=20)),
                ('muddat_kuni', models.IntegerField()),
                ('vazifa_fayli', models.FileField(blank=True, default=None, null=True, upload_to='uyga-vazifa-fayllar/')),
                ('guruh', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.guruhlar')),
                ('oqituvchi', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.oqituvchi')),
            ],
        ),
        migrations.CreateModel(
            name='Tashkilot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('joylashuvi', models.TextField(blank=True, default=None, null=True)),
                ('ochilgan_yili', models.DateTimeField(blank=True, default=None, null=True)),
                ('sohalar', models.ManyToManyField(to='main.Sohalar')),
                ('turi', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.tashkilotturlari')),
            ],
        ),
        migrations.CreateModel(
            name='Oquvchi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=50)),
                ('familiya', models.CharField(max_length=50)),
                ('sharif', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('tugilgan_kun', models.DateTimeField()),
                ('fanlar', models.ManyToManyField(to='main.Sohalar')),
                ('guruhi', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.guruhlar')),
                ('tashkilot', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.tashkilot')),
            ],
        ),
        migrations.AddField(
            model_name='oqituvchi',
            name='fanlar',
            field=models.ManyToManyField(to='main.Sohalar'),
        ),
        migrations.AddField(
            model_name='oqituvchi',
            name='guruhlari',
            field=models.ManyToManyField(to='main.Guruhlar'),
        ),
        migrations.AddField(
            model_name='oqituvchi',
            name='tashkilot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.tashkilot'),
        ),
        migrations.CreateModel(
            name='Mavzu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mavzu_matni', models.TextField()),
                ('mavzu_sanasi', models.DateTimeField()),
                ('mavzu_fayli', models.FileField(blank=True, default=None, null=True, upload_to='uyga-vazifa-fayllar/')),
                ('guruh', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.guruhlar')),
                ('oqituvchi', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.oqituvchi')),
            ],
        ),
        migrations.CreateModel(
            name='Javob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('javob_kuni', models.DateTimeField(auto_now_add=True)),
                ('javob_matni', models.TextField(blank=True, default=None, null=True)),
                ('javob_fayli', models.FileField(blank=True, default=None, null=True, upload_to='')),
                ('oquvchi', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.oquvchi')),
                ('uyga_vazifa', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.uygavazifa')),
            ],
        ),
        migrations.AddField(
            model_name='guruhlar',
            name='sohalar',
            field=models.ManyToManyField(to='main.Sohalar'),
        ),
        migrations.AddField(
            model_name='guruhlar',
            name='tashkilot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.tashkilot'),
        ),
        migrations.CreateModel(
            name='Baholar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baho', models.IntegerField()),
                ('fan', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.sohalar')),
                ('javob', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.javob')),
                ('oqituvchi', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.oqituvchi')),
                ('oquvchi', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.oquvchi')),
            ],
        ),
    ]
