# Generated by Django 3.2.3 on 2021-05-28 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sohalar',
            options={'verbose_name': 'Soha', 'verbose_name_plural': 'Sohalar'},
        ),
        migrations.AlterModelOptions(
            name='tashkilotturlari',
            options={'verbose_name': 'Tashkilot turi', 'verbose_name_plural': 'Tashkilot turlari'},
        ),
        migrations.AlterField(
            model_name='sohalar',
            name='asosiy_soha',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to='main.sohalar'),
        ),
    ]
